apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  name: micollab
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: my-micollab
  template:
    metadata:
      labels:
        run: my-micollab
    spec:
      containers:
      - image: gcr.io/integration-238016/micollab:9.0.0.2-06
        imagePullPolicy: IfNotPresent
        name: micollab
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
             - ALL
          privileged: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        micollab-label: micollab-node
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
