{{- if .Values.volume.mountEnabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.volume.persistentVolume}}
  namespace: {{.Release.Namespace}}
  labels:
    helm.sh/chart: {{ include "micollab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.volume.persistentVolumeSize}}
  storageClassName: standard
{{- end }}