apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loadbalancerservice.name }}
  namespace: {{.Release.Namespace}}
  labels:
    helm.sh/chart: {{ include "micollab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  clusterIP: {{ .Values.loadbalancerservice.clusterIP }}
  externalTrafficPolicy: Cluster
  ports:
  {{- range .Values.loadbalancerservice.ports }}
  - name: {{.name}}
    nodePort: {{.nodePort}}
    port: {{.port}}
    protocol: {{.protocol}}
    targetPort: {{.targetPort}}
  {{- end }}	

  selector:
    {{ .Values.deployment.labelSelector }}: {{ .Values.deployment.labelValue }}
  sessionAffinity: {{ .Values.loadbalancerservice.sessionAffinity }}
  type: {{ .Values.loadbalancerservice.type }}
