apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  name: {{ .Values.deployment.name }}
  namespace: {{.Release.Namespace}}
  labels:
    helm.sh/chart: {{ include "micollab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  progressDeadlineSeconds: {{ .Values.deployment.deadlineSec }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.limit }}
  selector:
    matchLabels:
      {{ .Values.deployment.labelSelector }}: {{ .Values.deployment.labelValue }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{ .Values.deployment.labelSelector }}: {{ .Values.deployment.labelValue }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}{{.Values.image.micollabimage}}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.deployment.name }}
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
             - ALL
          privileged: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
{{- if .Values.volume.volumeCreated }}		
        volumeMounts:
        - name: micollab-data
          mountPath: /var/lib/pgsql/10/data
          subPath: mnt/db/
        - name: micollab-data
          mountPath: /home/e-smith/db
          subPath: mnt/homeesmith/
        - name: micollab-data
          mountPath: /var/lib/ldap/
          subPath: mnt/ldap/
        - name: micollab-data
          mountPath: /etc/e-smith/db
          subPath: mnt/etc/
        - name: micollab-data
          mountPath: /var/log/awc
          subPath: mnt/awclogs/
        - name: micollab-data
          mountPath: /var/log/e-smith
          subPath: mnt/esmithlogs/		  
{{- end }}		  
      dnsPolicy: {{ .Values.deployment.policy }}
{{- if .Values.someSelector }}	  
      nodeSelector:
        {{ .Values.someSelector }}: {{ .Values.someSelectorValue }}
{{- end }}		
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- if .Values.volume.volumeCreated }}	  
      volumes:
      - name: micollab-data
        persistentVolumeClaim: 
          claimName: {{.Values.volume.persistentVolume}}
{{- end }}