{{- if .Values.persistentVolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.persistentVolume}}
  namespace: {{.Release.Namespace}}
  labels:
    helm.sh/chart: {{ include "micollab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.persistentVolumeSize}}
  storageClassName: standard
{{- end }}